# Jekyll configuration

name: Equal Parts
description: A roughly even mixture of technology, music, travelling and general contemplation.

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

permalink: /:categories/:year/:month/:title/
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'local_config.yml', '.git']
keep_files: ['.git']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      ongoing: true
  
  -
    scope:
      path: "archives"
    values:
      layout: "archive"
            
collections:
  projects:
    output: true
  testcoll:
    output: false
